### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by ScottHolden** [davidwengier/davidwengier.github.io#2]
GitHub now has https support! Woo!
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Looks like you need to remove and re-add the custom domain from the Pages section of repo settings to get it to request a cert (as it is at an apex, using A records). 😃

**Comment by ScottHolden** [comment]
Also enforce https would be awesome!

**Comment by davidwengier** [comment]
Yep. Tried that this morning, but still waiting for my DNS changes to propagate :P

**Comment by ScottHolden** [comment]
DNS looks good from here 👍

**Comment by davidwengier** [comment]
Tell that to Github? Unless I'm missing a step, I've removed and re-added the custom domain a half a dozen times today. Maybe I need to push something to kick it in the pants?

**Comment by davidwengier** [comment]
How many commits does it take to get to the center of an HTTP configuration?

https://github.com/davidwengier/davidwengier.github.io/commits/master

**Comment by davidwengier** [comment]
It verks! Its verking!

Not with www but this'll do :P
